-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v1.2.3
    hooks:
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: mixed-line-ending
        args: [--fix=lf]
        files: (?!.*third_party)^.*$ | (?!.*book)^.*$
    -   id: detect-private-key
        files: (?!.*third_party)^.*$ | (?!.*book)^.*$
    -   id: end-of-file-fixer
-   repo: local
    hooks:
    -   id: clang-format-check
        name: clang-format
        description: Format files with ClangFormat.
        entry: bash ./.clang_format.hook -i
        language: system
        files: \.(c|cc|cxx|cpp|cu|h|hpp|hxx|proto)$
-   repo: https://github.com/pre-commit/mirrors-yapf
    sha: v0.20.0
    hooks:
    -   id: yapf
        files: (.*\.(py|bzl)|BUILD|.*\.BUILD|WORKSPACE)$
